WOQL.and(
	WOQL.doctype("GitHubRepository")
        .label("GitHub Repository")
        .description("A GitHub repository of interest")
		.property("gitHub_repository_html_url", "xdd:url")
		    .label("GitHub Repository Url")
		.property("gitHub_repository_star", "scm:GitHubStar")
			.label("GitHub Repository Star")
		.property("gitHub_repository_commit", "scm:GitHubCommit")
			.label("GitHub Repository Commit")
		.property("gitHub_repository_issue", "scm:GitHubIssue")
			.label("GitHub Repository Issue")
		.property("gitHub_repo_pull_request", "scm:GitHubPullRequest")
			.label("GitHub Repository Pull Request")
			,
    WOQL.doctype("GitHubUser")
		.label("GitHub User")
		.description("A GitHub User")
		.property("gitHub_user_html_url", "xdd:url")
            .label("GitHub User Url")
		.property("gitHub_user_email", "xdd:email")
            .label("GitHub User Email")
		.property("gitHub_user_avatar", "xdd:url")
            .label("GitHub User Avatar")
		.property("gitHub_user_star", "scm:GitHubStar")
			.label("GitHub User Star")
		.property("gitHub_user_commit", "scm:GitHubCommit")
			.label("GitHub User Commit")
		.property("gitHub_user_issue", "scm:GitHubIssue")
			.label("GitHub User Issue")
		.property("gitHub_user_pull_request", "scm:GitHubPullRequest")
			.label("GitHub User Pull Request")
		,
    WOQL.add_class("GitHubStar")
        .label("GitHub Star")
		.property("starred_at", "dateTime")
			.label("Starred at")
		.property("unstarred_at", "dateTime")
			.label("Unstarred at")
		.property("action", "string")
			.label("Action"),
	WOQL.add_class("GitHubCommit")
        .label("GitHub Commit")
		.property("gitHub_commit_ref", "string")
			.label("GitHub Commit Ref")
		.property("gitHub_commit_message", "string")
			.label("GitHub Commit Message")
		.property("gitHub_commit_at", "dateTime")
			.label("GitHub Commit Created at")
		.property("gitHub_commit_url", "xdd:url")
			.label("GitHub Commit Url"),
	WOQL.add_class("GitHubIssue")
        .label("GitHub Issue")
		.property("gitHub_issue_state", "string")
			.label("GitHub Issue State")
		.property("gitHub_issue_url", "xdd:url")
			.label("GitHub Issue Url")
		.property("gitHub_issue_title", "string")
			.label("GitHub Issue Title")
		.property("gitHub_issue_body", "string")
			.label("GitHub Issue Body")
		.property("gitHub_issue_created_at", "dateTime")
			.label("GitHub Issue Created At")
		.property("gitHub_issue_updated_at", "dateTime")
			.label("GitHub Issue Updated At")
		.property("gitHub_issue_closed_at", "dateTime")
			.label("GitHub Issue Closed At"),
	WOQL.add_class("GitHubPullRequest")
        .label("GitHub Pull Request")
		.property("gitHub_pull_request_state", "string")
			.label("GitHub Pull Request State")
		.property("gitHub_pull_request_url", "xdd:url")
			.label("GitHub Pull Request Url")
		.property("gitHub_pull_request_title", "string")
			.label("GitHub Pull Request Title")
		.property("gitHub_pull_request_body", "string")
			.label("GitHub Pull Request Body")
		.property("gitHub_pull_request_created_at", "dateTime")
			.label("GitHub Pull Request Created At")
		.property("gitHub_pull_request_updated_at", "dateTime")
			.label("GitHub Pull Request Updated At")
		.property("gitHub_pull_request_closed_at", "dateTime")
			.label("GitHub Pull Request Closed At")
)
